#!/bin/sh
ng build --prod
git add -A && git commit -m "$1"
git push
cp -R /Users/hmmm/Documents/GitHub/kevintrankt/dist/kevintrankt/. /Users/hmmm/Documents/GitHub/kevintrankt.github.io
cd /Users/hmmm/Documents/GitHub/kevintrankt.github.io
git add -A && git commit -m "$1"
git push
cd /Users/hmmm/Documents/GitHub/kevintrankt/
